""" version which can be consumed from within the module """
VERSION_STR = "0.0.20"
DESCRIPTION = "pyanyzip is a module to help with dealing with compressed files transparently"
APP_NAME = "pyanyzip"
LOGGER_NAME = "pyanyzip"
